"""
raspa_mcp.generators — produce RASPA2 input definition files from structured args.

This module is the heart of the *full-custom* workflow: it lets a user (or LLM)
build any combination of CIF + force field + molecule definition without having
to memorise the picky text formats RASPA2 expects.

Two kinds of force-field files are easy to confuse — and getting them swapped
is a very common source of cryptic ``:#`` parse errors from RASPA2:

* ``force_field_mixing_rules.def`` — Lennard-Jones epsilon/sigma per atom type.
  This is what the simulation reads to compute pair interactions when no
  explicit override exists.
* ``force_field.def`` — *overwrite rules*: optional cross-pair tweaks, special
  shifted/truncated settings, etc. RASPA2 still requires this file to exist
  (with at least the "3 zeros" header) when ``Forcefield`` is set in
  ``simulation.input``. This file is **not** the place to list LJ parameters.

The generators below always emit syntactically correct content for these two
files, plus ``pseudo_atoms.def`` (atom registry) and per-molecule ``.def`` files.

All ``write_*`` helpers are sandbox-aware: the destination directory must
resolve inside ``RASPA_MCP_WORKSPACE_BASE`` (default ``~/raspa_workspaces``).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Iterable


# ─────────────────────────────────────────────────────────────────
# Sandbox helpers
# ─────────────────────────────────────────────────────────────────

def _workspace_base() -> Path:
    base_env = os.environ.get("RASPA_MCP_WORKSPACE_BASE", "").strip()
    base = Path(base_env).expanduser() if base_env else (Path.home() / "raspa_workspaces")
    return base.resolve()


def _resolve_inside_sandbox(work_dir: str) -> tuple[Path, str | None]:
    """Resolve ``work_dir`` and ensure it is inside the sandbox base.

    Returns (resolved_path, error_message_or_None).
    """
    try:
        target = Path(work_dir).expanduser().resolve()
        base = _workspace_base()
    except (OSError, RuntimeError) as e:
        return Path(work_dir), f"Cannot resolve paths: {e}"
    try:
        target.relative_to(base)
    except ValueError:
        return target, (
            f"work_dir {target} is outside allowed base {base}. "
            f"Set RASPA_MCP_WORKSPACE_BASE to override the allowed root."
        )
    return target, None


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


# ─────────────────────────────────────────────────────────────────
# 1. force_field.def  (overwrite rules — NOT mixing rules)
# ─────────────────────────────────────────────────────────────────

# RASPA2 minimal "3 zeros" form: declares zero overrides.
_MIN_FORCE_FIELD_DEF = """\
# RASPA2 force_field.def — OVERWRITE / EXTEND rules
# Generated by raspa_mcp.generators.
#
# IMPORTANT — do NOT confuse with force_field_mixing_rules.def!
#   * force_field_mixing_rules.def: Lennard-Jones epsilon/sigma per atom type.
#   * force_field.def (this file): cross-pair overrides and shift/tail rules.
#
# Format: each section starts with the *count* on its own line, followed by
# that many entries. Setting all three counts to 0 means "use only what is
# in force_field_mixing_rules.def". This is the safest default.

# Number of rules to overwrite the mixing rules
0

# Number of interactions to be defined explicitly
0

# Number of mixing-rule cross terms to overwrite
0
"""


def render_force_field_def(
    rules_to_overwrite: Iterable[dict] | None = None,
    interactions_to_define: Iterable[dict] | None = None,
    mixing_rules_to_overwrite: Iterable[dict] | None = None,
) -> str:
    """Render the contents of ``force_field.def``.

    Each parameter is an iterable of dicts; each dict carries the line text
    in the ``"line"`` key (raw form expected by RASPA2). Optional ``"comment"``
    is rendered as a ``#`` line above the entry.

    With no arguments this returns the minimal "3 zeros" form, which is what
    most users actually want when their LJ params live in
    ``force_field_mixing_rules.def``.
    """
    rules = list(rules_to_overwrite or [])
    interactions = list(interactions_to_define or [])
    mixings = list(mixing_rules_to_overwrite or [])

    if not rules and not interactions and not mixings:
        return _MIN_FORCE_FIELD_DEF

    parts: list[str] = [
        "# RASPA2 force_field.def — OVERWRITE / EXTEND rules",
        "# Generated by raspa_mcp.generators.",
        "#",
        "# Do NOT confuse with force_field_mixing_rules.def (LJ epsilon/sigma).",
        "",
        "# Number of rules to overwrite the mixing rules",
        str(len(rules)),
    ]
    for r in rules:
        if r.get("comment"):
            parts.append(f"# {r['comment']}")
        parts.append(str(r["line"]))

    parts += ["", "# Number of interactions to be defined explicitly", str(len(interactions))]
    for it in interactions:
        if it.get("comment"):
            parts.append(f"# {it['comment']}")
        parts.append(str(it["line"]))

    parts += ["", "# Number of mixing-rule cross terms to overwrite", str(len(mixings))]
    for m in mixings:
        if m.get("comment"):
            parts.append(f"# {m['comment']}")
        parts.append(str(m["line"]))

    return "\n".join(parts) + "\n"


# ─────────────────────────────────────────────────────────────────
# 2. force_field_mixing_rules.def
# ─────────────────────────────────────────────────────────────────

_VALID_MIXING_RULES = {"Lorentz-Berthelot", "Jorgensen"}
_VALID_TRUNCATIONS = {"shifted", "truncated"}


def render_force_field_mixing_rules_def(
    atom_types: Iterable[dict],
    general_mixing_rule: str = "Lorentz-Berthelot",
    general_truncation: str = "shifted",
    tail_corrections: bool = True,
) -> str:
    """Render the contents of ``force_field_mixing_rules.def``.

    ``atom_types`` items: ``{"name": str, "epsilon_K": float, "sigma_A": float,
    "interaction": str = "lennard-jones", "comment": str | None}``.
    """
    if general_mixing_rule not in _VALID_MIXING_RULES:
        raise ValueError(
            f"general_mixing_rule must be one of {sorted(_VALID_MIXING_RULES)}; "
            f"got {general_mixing_rule!r}"
        )
    if general_truncation not in _VALID_TRUNCATIONS:
        raise ValueError(
            f"general_truncation must be one of {sorted(_VALID_TRUNCATIONS)}; "
            f"got {general_truncation!r}"
        )

    atoms = list(atom_types)
    if not atoms:
        raise ValueError("atom_types must contain at least one entry.")

    lines: list[str] = [
        "# RASPA2 force_field_mixing_rules.def",
        "# Generated by raspa_mcp.generators.",
        "# Lennard-Jones epsilon/sigma per atom type. Cross terms are derived",
        "# from the general mixing rule below.",
        "",
        "# general rule for shifted vs truncated",
        general_truncation,
        "",
        "# general rule tail corrections",
        "yes" if tail_corrections else "no",
        "",
        "# number of defined interactions",
        str(len(atoms)),
        "",
        "# atom-type interaction-type epsilon/kB(K) sigma(A)",
    ]
    for a in atoms:
        if "name" not in a or "epsilon_K" not in a or "sigma_A" not in a:
            raise ValueError(
                "Each atom_type must have 'name', 'epsilon_K', 'sigma_A' "
                f"(got {a!r})"
            )
        comment = a.get("comment")
        if comment:
            lines.append(f"# {comment}")
        interaction = a.get("interaction", "lennard-jones")
        lines.append(
            f"{a['name']:<14} {interaction:<14} "
            f"{float(a['epsilon_K']):<10.4f} {float(a['sigma_A']):<10.4f}"
        )

    lines += [
        "",
        "# general mixing rule for Lennard-Jones",
        general_mixing_rule,
    ]
    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────
# 3. pseudo_atoms.def
# ─────────────────────────────────────────────────────────────────

_PSEUDO_HEADER = (
    "# type      print  as          chem  oxidation  mass        charge      "
    "polarization  B-factor  radii  connectivity  anisotropic  "
    "anisotropic-type  tinker-type"
)


def render_pseudo_atoms_def(atoms: Iterable[dict]) -> str:
    """Render the contents of ``pseudo_atoms.def``.

    Each ``atoms`` item must provide at minimum ``name``, ``chem``, ``mass``,
    ``charge``. Other fields default to RASPA2 typical values.
    """
    atom_list = list(atoms)
    if not atom_list:
        raise ValueError("atoms must contain at least one entry.")

    lines: list[str] = [
        "# RASPA2 pseudo_atoms.def — atom registry for the simulation.",
        "# Generated by raspa_mcp.generators.",
        "# All atom types referenced by simulation.input, *.def, or the CIF",
        "# (when UseChargesFromCIFFile=yes / UseAtomicNumbersFromCIFFile=yes)",
        "# must be listed here.",
        "",
        f"{len(atom_list)}",
        _PSEUDO_HEADER,
    ]
    for a in atom_list:
        for key in ("name", "chem", "mass", "charge"):
            if key not in a:
                raise ValueError(f"pseudo atom missing required key {key!r}: {a!r}")
        lines.append(
            f"{str(a['name']):<11} "
            f"{str(a.get('print', 'yes')):<6} "
            f"{str(a.get('print_as', a['name'])):<11} "
            f"{str(a['chem']):<5} "
            f"{int(a.get('oxidation', 0)):<10} "
            f"{float(a['mass']):<11.4f} "
            f"{float(a['charge']):<11.4f} "
            f"{float(a.get('polarization', 0.0)):<13.4f} "
            f"{float(a.get('b_factor', 1.0)):<9.3f} "
            f"{float(a.get('radii', 1.0)):<6.3f} "
            f"{int(a.get('connectivity', 0)):<13} "
            f"{float(a.get('anisotropic', 0.0)):<12.3f} "
            f"{str(a.get('anisotropic_type', 'absolute')):<17} "
            f"{int(a.get('tinker_type', 0))}"
        )
    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────
# 4. molecule .def
# ─────────────────────────────────────────────────────────────────

def render_molecule_def(
    molecule_name: str,
    critical_temperature_K: float,
    critical_pressure_Pa: float,
    acentric_factor: float,
    atoms: list[dict],
    bonds: list[tuple[int, int, str]] | None = None,
    bends: list[tuple[int, int, int, str]] | None = None,
    torsions: list[tuple[int, int, int, int, str]] | None = None,
    rigid: bool = True,
    n_groups: int = 1,
) -> str:
    """Render a RASPA2 molecule ``.def`` file.

    ``atoms``: ``[{"type": str, "x": float, "y": float, "z": float}, ...]`` —
    coordinates are in Å relative to the molecule centre of mass.

    ``bonds`` / ``bends`` / ``torsions``: tuples of atom indices ending in the
    RASPA2 interaction keyword (e.g. ``"RIGID_BOND"``, ``"HARMONIC_BOND ..."``).
    """
    if not atoms:
        raise ValueError("atoms must contain at least one entry.")

    bonds = list(bonds or [])
    bends = list(bends or [])
    torsions = list(torsions or [])

    counts_line = (
        f"0 {len(bonds)} 0 {len(bends)} 0 {len(torsions)} 0 0 0 0 0 0 0"
    )

    lines: list[str] = [
        f"# RASPA2 molecule definition for {molecule_name}",
        "# Generated by raspa_mcp.generators.",
        "",
        "# critical constants: Temperature [K], Pressure [Pa], acentric factor [-]",
        f"{float(critical_temperature_K):.4f}",
        f"{float(critical_pressure_Pa):.4f}",
        f"{float(acentric_factor):.5f}",
        "",
        "# Number of Atoms",
        str(len(atoms)),
        "",
        "# Number of Groups",
        str(n_groups),
        "",
        f"# Group flexibility (rigid={rigid})",
        ("rigid" if rigid else "flexible"),
        "",
        "# Number of atoms in this group",
        str(len(atoms)),
        "",
        "# Atomic Positions: index  type  x(A)  y(A)  z(A)",
    ]
    for i, a in enumerate(atoms):
        for key in ("type", "x", "y", "z"):
            if key not in a:
                raise ValueError(f"atom #{i} missing key {key!r}: {a!r}")
        lines.append(
            f"{i:<3} {str(a['type']):<10} "
            f"{float(a['x']):>9.4f} {float(a['y']):>9.4f} {float(a['z']):>9.4f}"
        )

    lines += [
        "",
        "# Chiral  Bond  BondDipoles  Bend  UreyBradley  Torsion  ImproperTorsion  OutOfPlane  Bond/Bond  Bond/Bend  Bend/Bend  StretchTorsion  BendTorsion",
        counts_line,
        "",
        "# Bond stretch: atom1 atom2 type [params]",
    ]
    for b in bonds:
        i, j, kind = b[0], b[1], b[2]
        lines.append(f"{i} {j} {kind}")

    if bends:
        lines += ["", "# Bend: atom1 atom2 atom3 type [params]"]
        for b in bends:
            lines.append(f"{b[0]} {b[1]} {b[2]} {b[3]}")

    if torsions:
        lines += ["", "# Torsion: atom1 atom2 atom3 atom4 type [params]"]
        for t in torsions:
            lines.append(f"{t[0]} {t[1]} {t[2]} {t[3]} {t[4]}")

    lines += ["", "# Number of config moves", "0", ""]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────
# Disk-writing wrappers (sandbox-aware)
# ─────────────────────────────────────────────────────────────────

def write_force_field_def(work_dir: str, **kwargs: Any) -> dict:
    target, err = _resolve_inside_sandbox(work_dir)
    if err:
        return {"success": False, "errors": [err]}
    content = render_force_field_def(**kwargs)
    path = target / "force_field.def"
    _write_text(path, content)
    return {
        "success": True,
        "path": str(path),
        "content": content,
        "warning": (
            "force_field.def holds OVERWRITE rules only. Lennard-Jones epsilon/sigma "
            "belong in force_field_mixing_rules.def. Mixing them up causes ':#' "
            "parse errors."
        ),
    }


def write_force_field_mixing_rules_def(work_dir: str, **kwargs: Any) -> dict:
    target, err = _resolve_inside_sandbox(work_dir)
    if err:
        return {"success": False, "errors": [err]}
    content = render_force_field_mixing_rules_def(**kwargs)
    path = target / "force_field_mixing_rules.def"
    _write_text(path, content)
    return {"success": True, "path": str(path), "content": content}


def write_pseudo_atoms_def(work_dir: str, atoms: list[dict]) -> dict:
    target, err = _resolve_inside_sandbox(work_dir)
    if err:
        return {"success": False, "errors": [err]}
    content = render_pseudo_atoms_def(atoms)
    path = target / "pseudo_atoms.def"
    _write_text(path, content)
    return {"success": True, "path": str(path), "content": content}


def write_molecule_def(
    work_dir: str,
    molecule_name: str,
    subdirectory: str = "TraPPE",
    **kwargs: Any,
) -> dict:
    target, err = _resolve_inside_sandbox(work_dir)
    if err:
        return {"success": False, "errors": [err]}
    content = render_molecule_def(molecule_name=molecule_name, **kwargs)
    path = target / "molecules" / subdirectory / f"{molecule_name}.def"
    _write_text(path, content)
    return {
        "success": True,
        "path": str(path),
        "content": content,
        "hint": (
            f"In simulation.input, set: MoleculeDefinition {subdirectory.lower()} "
            f"if you want RASPA2 to look in ./molecules/{subdirectory}/."
        ),
    }
